binary_sensor:
  - platform: ping  #3 indica si PC encendido
    host: 192.168.1.5
    name: PC encendido
    count: 4
    scan_interval: 37

  - platform: ping
    host: www.google.es
    name: Online Internet
    count: 4
    scan_interval: 100

  - platform: workday
    country: ES
    province: CT

  - platform: meteoalarm
    country: 'ES'
    province: 'Litoral de Barcelona'
    language: es

