input_boolean: # Si está encendida, aviso pastilla
  tomar_pastilla:
    name: Pastilla
    icon: mdi:pill

  topbar_config:
    name: Menú de configuración

  encender_ordenador: # si pasa a on trigger encender_ordenador
    name: Endender ordenador
    icon: 'mdi:desktop-classic'

  aviso_tablet: #lanza automatización avisar apagar tablet martí
    name: Aviso apagado tablet Martí
    icon: 'mdi:tablet-android'

  modo_kiosko: # indica si queremos usar modo kiosko o no
    name: Activar modo kiosko
    icon: fas:desktop

  mostrar_horseshoe:
    name: Mostrar Horse Shoe
    icon: mdi:horseshoe

  avisar_pastillas_movil: # aviso pastilla al móvil
    name: Avisar pastillas móvil
    icon: mdi:pill

  aviso_actividad_pc:
    name: Avisa encendidos y apagados PC
    icon: mdi:alarm-light-outline

  # para activar cosas desde google assistant
  cenando:
    name: escena cenando

  relax:
    name: escena relax

  a_cocinar:
    name: a cocinar

  a_la_ducha:
    name: a la ducha



# --------------------------------- Mapa del tiempo -------------------------------------

# Para determinar qué mapa del tiempo mostramos
  boton1:
    name: Ver mapa 1
    initial: true
  boton2:
    name: Ver mapa 2
    initial: false
  boton3:
    name: Ver mapa 3
    initial: false
  boton4:
    name: Ver mapa 4
    initial: false    

  play_pausa_mapa:
    name: Play/Pausa mapas_tiempo
    initial: true

  lluvia_proxima:
    name: Lluvia proxima
    initial: false

  # si se detecta caída se pone a true. Para diferenciar de caída internet
  red_electrica_caida:
    initial: false