input_number:

  x_pos:
    name: Posición X
    initial: 50
    min: 0
    max: 100
    step: 1

  y_pos:
    name: Posición Y
    initial: 50
    min: 0
    max: 100
    step: 1  

  backup_volumen:
    name: Guarda volumen player para después restablecer
    min: 0
    max: 1