input_boolean: # Si está encendida, aviso pastilla
  tomar_pastilla:
    name: Pastilla
    icon: mdi:pill

  encender_ordenador: # si pasa a on trigger encender_ordenador
    name: Endender ordenador
    icon: 'mdi:desktop-classic'

  aviso_tablet: #lanza automatización avisar apagar tablet martí
    name: Aviso apagado tablet Martí
    icon: 'mdi:tablet-android'

  modo_kiosko: # indica si queremos usar modo kiosko o no
    name: Activar modo kiosko
    icon: fas:desktop

  avisar_pastillas_movil: # el aviso diario de la pastilla, lo envía al móvil? Útil en vacaciones
    name: Avisar pastillas móvil
    icon: mdi:pill
  # --------------------- Asociados a las pantallas --------------------------------
  screen_home: 
    name: pantalla home
    icon: fas:house-user

  screen_lights: # panta
    name: pantalla luces
    icon: fas:lightbulb

  screen_weather:
    name: pantalla meteo
    icon: fas:cloud-sun



# --------------------------------- Mapa del tiempo -------------------------------------

# Para determinar qué mapa del tiempo mostramos
  boton1:
    name: Ver mapa 1
    initial: true
  boton2:
    name: Ver mapa 2
    initial: false
  boton3:
    name: Ver mapa 3
    initial: false
  boton4:
    name: Ver mapa 4
    initial: false    

  play_pausa_mapa:
    name: Play/Pausa mapas_tiempo
    initial: true

  lluvia_proxima:
    name: Lluvia proxima
    initial: false


