media_player: # -----------------------------------------------------------------------------------------------------------------
  - platform: yamaha_musiccast
    host: 192.168.1.31
    port: 5005
    
  - platform: yamaha_musiccast
    host: 192.168.1.32
    port: 5006
    
  - platform: yamaha_musiccast
    host: 192.168.1.30
    port: 5007
