# ----------------------- Establece qué grabamos y qué no --------------------
# https://www.home-assistant.io/components/recorder/
# https://community.home-assistant.io/t/rpi-hassio-synology-nas-maria-db-for-logging/64012

recorder:
  db_url: mysql://jordiam:5SCwf9kTyezdGqp@192.168.1.9:3307/ha_2020?charset=utf8
  purge_keep_days: 21   # días a mantener después del purge
  purge_interval: 1
  exclude:
    event_types:
      - call_service
      - hacs/repository
  include:
    domains:
      - sensor

# https://www.home-assistant.io/integrations/history/
# history: en principio no ponemos nada, entonces lo hará de los mismo elementos del recorder