  type: horizontal-stack
  cards:
    - type: picture-elements
      image: /local/img/topv9-left.png
      elements:
        - type: image
          image: /local/img/topbar/old/home.png
          tap_action:
            action: navigate
            navigation_path: start
          style:
            top: 50%
            left: 4%
            width: 5.5%
            border-radius: 15px
            border: solid 1px rgba(100,100,100,0.3)
            color: "#999999"
            box-shadow: 3px 3px rgba(0,0,0,0.4)

        - type: image
          image: /local/img/topbar/old/pi.png
          tap_action:
            action: navigate
            navigation_path: pi
          style:
            top: 50%
            left: 11%
            width: 5.5%
            border-radius: 15px
            border: solid 1px rgba(100,100,100,0.3)
            color: "#999999"
            box-shadow: 3px 3px rgba(0,0,0,0.4)

        - type: image
          image: /local/img/topbar/old/info.png
          tap_action:
            action: navigate
            navigation_path: info

          style:
            top: 50%
            left: 18%
            width: 5.5%
            border-radius: 15px
            border: solid 1px rgba(100,100,100)
            #color: "#999999"
            #box-shadow: 3px 3px rgba(0,0,0,0.4)

        - type: image
          image: /local/img/topbar/old/config.png
          tap_action:
            action: navigate
            navigation_path: config
          style:
            top: 50%
            left: 25%
            width: 5.5%
            border-radius: 15px
            border: solid 1px rgba(100,100,100,0.3)
            color: "#999999"
            box-shadow: 3px 3px rgba(0,0,0,0.4)

