title: 300_eltiempo
path: eltiempo
icon: mdi:weather-partly-snowy-rainy
panel: true
cards:

  - type: vertical-stack           
    cards:    
      - !include /config/lovelace1/__menu__.yaml

      - type: custom:layout-card
        layout: horizontal # auto vertical horizontal
        column_num: 3
        # max_columns: 6
        # column_width: 50
        max_width: [33%, 33%, 33%]
        min_height: 100
        rebuild: 1000
        cards:
          - type: vertical-stack             
            cards:   
              - type: custom:weather-card
                entity: weather.dark_sky 

              - type: conditional
                conditions:
                  - entity: input_select.mapas_tiempo
                    state: 'Mapa1'
                card:
                  type: picture
                  image: 'https://api.sat24.com/animated/SP/rainTMC/2/Romance%20Standard%20Time/6988807'


              - type: conditional
                conditions:
                  - entity: input_select.mapas_tiempo
                    state: 'Mapa2'
                card:
                  type: picture
                  image:  'http://api.sat24.com/animated/EU/visual/2/Central%20European%20Standard%20Time/571447'

              - type: conditional
                conditions:
                  - entity: input_select.mapas_tiempo
                    state: 'Mapa3'
                card:
                  type: picture
                  image:  'https://api.sat24.com/animated/SP/infraPolair/2/Romance%20Standard%20Time/3835578'

              - type: conditional
                conditions:
                  - entity: input_select.mapas_tiempo
                    state: 'Mapa4'
                card:
                  type: picture
                  image:  'http://api.sat24.com/animated/SP/visual/2/Central%20European%20Standard%20Time/6154800'


              - type: horizontal-stack
                cards:
                  - type: "custom:button-card"
                    show_name: false
                    entity: input_boolean.boton1
                    color_type: card
                    color: rgb(66, 134, 244)
                    icon: mdi:numeric-1-box-outline
                  - type: "custom:button-card"
                    show_name: false
                    entity:  input_boolean.boton2
                    color_type: card
                    color: rgb(66, 134, 244)
                    icon: mdi:numeric-2-box-outline
                  - type: "custom:button-card"
                    show_name: false
                    entity:  input_boolean.boton3
                    color_type: card
                    color: rgb(66, 134, 244)
                    icon: mdi:numeric-3-box-outline
                  - type: "custom:button-card"
                    show_name: false
                    entity:  input_boolean.boton4
                    color_type: card
                    color: rgb(66, 134, 244)
                    icon: mdi:numeric-4-box-outline
                  - type: "custom:button-card"
                    show_name: false
                    entity:  input_boolean.play_pausa_mapa
                    color_type: card
                    color: rgb(66, 134, 244)
                    icon: mdi:play-box-outline



          - type: vertical-stack           
            cards: 

              - type: iframe
                url: https://embed.windy.com/embed2.html?lat=41.706&lon=1.571&zoom=7&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=true&type=map&location=coordinates&detail=&detailLat=41.389&detailLon=2.161&metricWind=default&metricTemp=default&radarRange=-1
                aspect_ratio: 80%

              - type: iframe
                url: https://embed.windy.com/embed2.html?lat=41.722&lon=1.582&zoom=7&level=surface&overlay=rainAccu&menu=&message=&marker=&calendar=&pressure=true&type=map&location=coordinates&detail=&detailLat=41.393&detailLon=2.153&metricWind=default&metricTemp=default&radarRange=-1
                aspect_ratio: 80%



# viento <iframe width="650" height="450" src="https://embed.windy.com/embed2.html?lat=41.706&lon=1.571&zoom=7&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=true&type=map&location=coordinates&detail=&detailLat=41.389&detailLon=2.161&metricWind=default&metricTemp=default&radarRange=-1" frameborder="0"></iframe>
# lluvia <iframe width="650" height="450" src="https://embed.windy.com/embed2.html?lat=41.722&lon=1.582&zoom=7&level=surface&overlay=rainAccu&menu=&message=&marker=&calendar=&pressure=true&type=map&location=coordinates&detail=&detailLat=41.393&detailLon=2.153&metricWind=default&metricTemp=default&radarRange=-1" frameborder="0"></iframe>
# <iframe width="650" height="450" src="https://embed.windy.com/embed2.html?lat=41.389&lon=2.161&zoom=7&level=surface&overlay=temp&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=41.389&detailLon=2.161&metricWind=default&metricTemp=default&radarRange=-1" frameborder="0"></iframe>


          # https://github.com/gadgetchnnel/lovelace-entity-markdown-card
          - type: vertical-stack             
            cards:   
              - type: markdown
                content: >
                  ## Hoy

                  {{ states("sensor.dark_sky_hourly_summary") }}

              - type: markdown
                content: >
                  ## Próximos días

                  {{ states("sensor.dark_sky_daily_summary") }}   

              - type: horizontal-stack
                cards:
                  - type: glance
                    title: Fase Lunar
                    show_state: false
                    show_name: false
                    style: |
                        ha-card {
                          font-variant: small-caps;
                        }
                        .card-header {
                          font-size: 24px;
                        }

                    entities:
                      - sensor.moonphases
                  - type: custom:gap-card


