title: 520_spotify
path: spotify
icon: mdi:spotify
panel: true
cards:

  - type: vertical-stack           
    cards:    
      - !include /config/lovelace1/000_top_barv2.yaml
   

        #****************************************************************************************************************
        #****************************************************************************************************************
        #                       ALTAVOCES DE CASA. SE MUESTRAN SOLO EN LA PRIMERA PANTALLA
        #****************************************************************************************************************
        #****************************************************************************************************************

      - type: conditional
        conditions:
          - entity: input_boolean.caratulas1
            state: "on"
        card:
          #*****************************************   C O C I N A   *****************************************************
          type: horizontal-stack                                                # ************** SIN SONAR ***************
          cards:
            - type: conditional
              conditions:
                - entity: media_player.altavoz_cocina_main
                  state_not: "playing"
                - entity: media_player.altavoz_cocina_main
                  state_not: "paused"    
              card:
                  type: picture-entity
                  image: /local/img/lovelace/cocinav4.png
                  # entity: media_player.altavoz_cocina_main
                  entity: input_boolean.musica_cocina
                  show_name: false
                  show_state: false
                  tap_action:
                    action: call-service
                    # service: script.pon_musica_cocina
                    service: script.activa_spotify8
                    service_data: {"entidad":"input_boolean.musica_cocina"}
                      #entidad: "media_player.altavoz_cocina_main" 
                  double_tap_action:
                    action: call-service
                    service: script.pon_radio
                    service_data:
                      entidad: "media_player.altavoz_cocina_main"
                      booleano: "input_boolean.musica_cocina"

            - type: conditional                                                 # ************** SONANDO  ****************
              conditions:               # ****************  como Picture-elements no permite un OR, hay que ponerlo 2 veces
                - entity: media_player.altavoz_cocina_main
                  state: "playing"
              card:
                  type: custom:mini-media-player
                  entity: media_player.altavoz_cocina_main
                  artwork: cover  # cover  full-cover none full-cover-fit
                  source: icon   # full  icon
                  more_info: true 
                  info: scroll   #short scroll    
                  scale: 1.1

            - type: conditional                                                 # ************** SONANDO  ****************
              conditions:
                - entity: media_player.altavoz_cocina_main
                  state: "paused"
              card:
                  type: custom:mini-media-player
                  entity: media_player.altavoz_cocina_main
                  artwork: cover  # cover  full-cover none full-cover-fit
                  source: icon   # full  icon
                  more_info: true 
                  info: scroll   #short scroll    

              #*****************************************   L A V A B O    *************************************************
            - type: conditional                                                  # ************** SIN SONAR ***************
              conditions:
                - entity: media_player.altavoz_lavabo_main
                  state_not: "playing"
              card:
                  type: picture-entity
                  image: /local/img/lovelace/lavabov4.png
                  #entity: media_player.altavoz_lavabo_main
                  entity: input_boolean.musica_lavabo
                  show_name: false
                  show_state: false
                  tap_action:
                    action: call-service
                    # service: script.pon_musica_lavabo
                    service: script.activa_spotify8
                    service_data: {"entidad":"input_boolean.musica_lavabo"}

                  double_tap_action:
                    action: call-service
                    service: script.pon_radio
                    service_data:
                      entidad: "media_player.altavoz_lavabo_main"
                      booleano: "input_boolean.musica_lavabo"                

            - type: conditional                                                 # ************** SONANDO  ****************
              conditions:
                - entity: media_player.altavoz_lavabo_main
                  state: "playing"
              card:
                  type: custom:mini-media-player
                  entity: media_player.altavoz_lavabo_main
                  artwork: cover  # cover  full-cover none full-cover-fit
                  source: icon   # full  icon
                  more_info: true 
                  info: scroll   #short scroll 

            - type: conditional                                                 # ************** SONANDO  ****************
              conditions:
                - entity: media_player.altavoz_lavabo_main
                  state: "paused"
              card:
                  type: custom:mini-media-player
                  entity: media_player.altavoz_lavabo_main
                  artwork: cover  # cover  full-cover none full-cover-fit
                  source: icon   # full  icon
                  more_info: true 
                  info: scroll   #short scroll 


              #*****************************************   N I L    *******************************************************
            - type: conditional                                                  # ************** SIN SONAR ***************
              conditions:
                - entity: media_player.altavoz_nil_main
                  state_not: "playing"
              card:
                  type: picture-entity
                  image: /local/img/lovelace/nilv4.png
                  #entity: media_player.altavoz_nil_main
                  entity: input_boolean.musica_nil
                  show_name: false
                  show_state: false
                  tap_action:
                    action: call-service
                    service: script.activa_spotify8
                    service_data: {"entidad":"input_boolean.musica_nil"}
                  double_tap_action:
                    action: call-service
                    service: script.pon_radio
                    service_data:
                      entidad: "media_player.altavoz_nil_main"
                      booleano: "input_boolean.musica_nil"

            - type: conditional                                                 # ************** SONANDO  ****************
              conditions:
                - entity: media_player.altavoz_nil_main
                  state: "playing"
              card:
                  type: custom:mini-media-player
                  entity: media_player.altavoz_nil_main
                  artwork: cover  # cover  full-cover none full-cover-fit
                  source: icon   # full  icon
                  more_info: true 
                  info: scroll   #short scroll    


            - type: conditional                                                 # ************** SONANDO  ****************
              conditions:
                - entity: media_player.altavoz_nil_main
                  state: "paused"
              card:
                  type: custom:mini-media-player
                  entity: media_player.altavoz_nil_main
                  artwork: cover  # cover  full-cover none full-cover-fit
                  source: icon   # full  icon
                  more_info: true 
                  info: scroll   #short scroll  

 
        # El código para el altavoz del lavabo venía aquí. Se ha guardado en 400_spotify_comedor.txt hasta que se arregle spotcast

        #****************************************************************************************************************
        #****************************************************************************************************************
        #                           PESTAÑAS PARA SELECCIONAR PÁGINA DE CARÁTULAS
        #****************************************************************************************************************
        #****************************************************************************************************************

      - type: horizontal-stack
        cards:

          - type: custom:auto-entities
            card:
              type: glance
              show_name: false
              show_state: false 
              style: 
                "--paper-item-icon-color": lime
                "--iron-icon-stroke-color": green
                "--iron-icon-height": 41px
                "--iron-icon-width": 41px

            filter:
              include:
                - entity_id: "*caratulas*"  # muestra todos los input_boolean.caratulas? que encuentre
                  options:
                    tap_action:
                      action: call-service
                      service: script.paginacaratula
                      service_data:
                      # Note the magic value this.entity_id here
                        lista: this.entity_id
              exclude:
                - domain: group


            ####################################### CONTROL DE VOLUMEN ##################################
          - type: conditional
            conditions:
              - entity: input_boolean.musica_lavabo
                state: "on"
            card:
              type: entities
              entities:
                - type: custom:slider-entity-row
                  entity: media_player.altavoz_lavabo_main
                  #full_row: true

          - type: conditional
            conditions:
              - entity: input_boolean.musica_cocina
                state: "on"
            card:
              type: entities
              entities:
                - type: custom:slider-entity-row
                  entity: media_player.altavoz_cocina_main
                  #full_row: true

          - type: conditional
            conditions:
              - entity: input_boolean.musica_nil
                state: "on"
            card:
              type: entities
              entities:
                - type: custom:slider-entity-row
                  entity: media_player.altavoz_nil_main
                  #full_row: true

          - type: conditional
            conditions:
              - entity: media_player.spotify_bitmap
                state: "unavailable"
            card:
              type: button
              name: Error SPOTIFY
              # icon: 'mdi:alert-circle'  Si lo pongo, sale muy grande
              icon_height: 40

        #****************************************************************************************************************
        #****************************************************************************************************************
        #              DIFERENTES PÁGINAS CON LAS CARÁTULAS. SE MUESTRAN EN EL ORDEN QUE ESTÁN EN SPOTIFY
        #****************************************************************************************************************
        #****************************************************************************************************************

      - type: conditional
        conditions:
          - entity: input_boolean.caratulas1
            state: "on"
        card:
            type: "custom:spotify-playlist-card"
            sensor: sensor.playlist
            columns: 6
            grid_gap: '3px'
            show_playlist_titles: true
            gradient_level: 0.8
            shuffle: true
            playback_method: spotify
            speaker_entity: media_player.spotify_bitmap

      - type: conditional
        conditions:
          - entity: input_boolean.caratulas2
            state: "on"
        card:
            type: "custom:spotify-playlist-card"
            sensor: sensor.playlist2
            columns: 6
            grid_gap: '3px'
            show_playlist_titles: true
            gradient_level: 0.8
            shuffle: true
            playback_method: spotify
            speaker_entity: media_player.spotify_bitmap

      - type: conditional
        conditions:
          - entity: input_boolean.caratulas3
            state: "on"
        card:
            type: "custom:spotify-playlist-card"
            sensor: sensor.playlist3
            columns: 6
            grid_gap: '3px'
            show_playlist_titles: true
            gradient_level: 0.8
            shuffle: true
            playback_method: spotify
            speaker_entity: media_player.spotify_bitmap

      - type: conditional
        conditions:
          - entity: input_boolean.caratulas4
            state: "on"
        card:
            type: "custom:spotify-playlist-card"
            sensor: sensor.playlist4
            columns: 6
            grid_gap: '3px'
            show_playlist_titles: true
            gradient_level: 0.8
            shuffle: true
            playback_method: spotify
            speaker_entity: media_player.spotify_bitmap

      - type: conditional
        conditions:
          - entity: input_boolean.caratulas5
            state: "on"
        card: []
