title: 850_config
path: config
icon: mdi:cog
panel: true
cards:
  - type: vertical-stack           
    cards:    
      - !include /config/lovelace1/__menu__.yaml

      - type: markdown
        content: |
           Pantalla de configuración

      - type: horizontal-stack             # Fila 1 ------------------------------
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - type: section
                label: ------- INTRFICIE -------
#              - entity: input_boolean.aleatorio_automatico
              - entity: input_boolean.modo_kiosko
              - entity: input_boolean.avisar_pastillas_movil
              - entity: input_boolean.mostrar_horseshoe
              - type: section
                label: -------- ALARMAS --------
              - entity: input_boolean.aviso_familia
              - entity: input_boolean.aviso_nadie
              - entity: input_boolean.aviso_desconocido
              - entity: input_boolean.aviso_durmiendo
              - entity: input_boolean.aviso_despierto
              - entity: input_boolean.aviso_actividad_pc
              - entity: input_boolean.notificar_errores

          - type: vertical-stack
            cards:
              - type: entities
                title: Temporizador
                show_header_toggle: false
                entities:
                  - entity: timer.temporizador
                    style: |
                      .text-content {
                        font-size: 30px; 
                      }
                  - entity: input_number.minutero
                  - entity: input_number.preaviso
                  - entity: input_boolean.activa_temporizador
                  - entity: input_select.mensaje_aviso
              - type: glance
                title: Restore
                entities:
                  #- entity: zone.home
                  #  icon: 'mdi:restart'
                  #  name: Lovelace
                  #  tap_action:
                  #    action: call-service
                  #    service: frontend.reload_themes
                  - entity: zone.home  # no sirve para nada, pero es obligatorio indicar una entidad
                    icon: 'mdi:restart'
                    name: Home Assistant (Soft)
                    tap_action:
                      action: call-service
                      service: homeassistant.restart
                  - entity: zone.home
                    icon: 'mdi:restart'
                    name: Server (Hard)
                    tap_action:
                      action: call-service
                      service: hassio.host_reboot

                # Muestra entidades "ROTAS" (unknow)
              - type: custom:auto-entities
                card:
                  type: entities
                  title: Entidades rotas
                  show_header_toggle: false
                filter:
                  include:
                    - state: "unknown"
                  exclude:
                    - entity_id: group.*


          - type: entities
            # title: ENTITIES 
            show_header_toggle: false
            entities:
              - type: section
                label: TAREAS
              - entity: script.full_backup_a_drive
                secondary_info: last-changed
              - entity: input_boolean.encender_ordenador
              - entity: input_boolean.aviso_tablet
              - type: section
                label: ------- CONTROL -------
              - entity: input_select.quien_en_casa
              - entity: sensor.hay_alguien
              - entity: sensor.hay_alguien_conocido
              - entity: sensor.hay_alguien_desconocido

          - type: entities
            show_header_toggle: false
            entities:
              - type: section
                label: ENTIDADES
              - entity: input_select.hay_cole
              - entity: input_select.control_volumen
              - entity: input_boolean.tomar_pastilla
              - entity: automation.sonar_timbre
              - entity: input_select.mapas_tiempo
              #- entity: input_boolean.iguala_luces
              - entity: input_boolean.vacaciones
              - entity: input_boolean.modo_fiesta


              #- entity:  automation.llegando_a_casa_home
