- type: horizontal-stack
  cards:
    - type: image
      image: /local/img/topbar/old/folder_options.png
      entity: input_boolean.topbar_config
      tap_action:
        action: toggle
      style:
        top: 50%
        left: 83%
        width: 5.5%
        border-radius: 15px
        border: solid 1px rgba(100,100,100,0.3)
        color: "#999999"
        box-shadow: 3px 3px rgba(0,0,0,0.4)




    - type: icon
      icon: mdi:overscan
      entity: input_boolean.modo_kiosko
      tap_action:
        action: toggle
      style: 
        top: 40%
        left: 90%
        transform: scale(2,2)

    - type: icon
      icon: mdi:volume-high
      tap_action:
        action: call-service
        service: browser_mod.command

        service_data:
          command: popup
          title: Mediaplayers
          deviceID:
            - this
          large: true
          style:
              border-radius: 20px
              --ha-card-border-radius: 20px
              --ha-card-background: grey

          card:
            type: vertical-stack
            cards:

              - type: custom:mini-media-player
                style: |
                  ha-card {
                    border: 2px solid grey;
                    margin: auto;
                    width: 700px;
                  }
                  .mmp-player {
                    height: 120px;
                    font-size: 18px !important;
                    background-image: url("/local/img/mp/lavabo.png") !important;
                  }
                entity: media_player.altavoz_lavabo_main
                artwork: cover  # cover  full-cover none full-cover-fit
                source: icon   # full  icon
                more_info: true 
                info: scroll   #short scroll 
                scale: 1
                hide:
                  - shuffle: false                   

              - type: custom:mini-media-player
                style: |
                  ha-card {
                    border: 2px solid grey;
                    margin: auto;
                    width: 700px;
                  }
                  .mmp-player {
                    height: 120px;
                    font-size: 18px !important;
                    background-image: url("/local/img/mp/cocina.png") !important;
                  }
                entity: media_player.altavoz_cocina_main
                artwork: cover  # cover  full-cover none full-cover-fit
                source: icon   # full  icon
                more_info: true 
                info: scroll   #short scroll                    

              - type: custom:mini-media-player
                style: |
                  ha-card {
                    border: 2px solid grey;
                    margin: auto;
                    width: 700px;
                  }
                  .mmp-player {
                    height: 120px;
                    font-size: 18px !important;
                    background-image: url("/local/img/mp/nil.png") !important;
                  }
                entity: media_player.altavoz_nil_main
                artwork: cover  # cover  full-cover none full-cover-fit
                source: icon   # full  icon
                more_info: true 
                info: scroll   #short scroll                    

              - type: custom:mini-media-player
                style: |
                  ha-card {
                    border: 2px solid grey;
                    margin: auto;
                    width: 700px;
                  }
                  .mmp-player {
                    height: 120px;
                    font-size: 18px !important;
                    background-image: url("/local/img/mp/superyo.png") !important;
                  }
                entity: media_player.superyo
                artwork: cover  # cover  full-cover none full-cover-fit
                source: icon   # full  icon
                more_info: true 
                info: scroll   #short scroll                    

              
              - type: custom:mini-media-player
                style: |
                  ha-card {
                    border: 2px solid grey;
                    margin: auto;
                    width: 700px;
                  }
                  .mmp-player {
                    height: 120px;
                    font-size: 18px !important;
                    background-image: url("/local/img/mp/miniyo.png") !important;
                  }
                entity: media_player.miniyo
                artwork: cover  # cover  full-cover none full-cover-fit
                source: icon   # full  icon
                more_info: true 
                info: scroll   #short scroll    
      style: 
        top: 40%
        left: 95%
        transform: scale(2,2)