# ---------------------------------------------- REGLETA 1 ----------------------------------------------
- type: picture-elements
  image: /local/img/lovelace/regleta1v2.png
  elements:
    - type: state-icon
      icon: mdi:power
      entity: switch.enchufe_canal_plus
      tap_action:
        action: toggle
      style:
        top: 15%
        left: 13%
        transform: scale(2,2)
        "--paper-item-icon-color": red
        "--paper-item-icon-active-color": green

    - type: state-icon
      icon: mdi:power
      entity: switch.enchufe_pioneer
      tap_action:
        action: toggle
      style:
        top: 15%
        left: 32%
        transform: scale(2,2)
        "--paper-item-icon-color": red
        "--paper-item-icon-active-color": green
                 
    - type: state-icon
      icon: mdi:power
      entity: switch.enchufe_libre
      tap_action:
        action: toggle
      style:
        top: 15%
        left: 51%
        transform: scale(2,2)
        "--paper-item-icon-color": red
        "--paper-item-icon-active-color": green


    - type: state-icon
      icon: mdi:power
      entity: switch.enchufe_nvidia
      tap_action:
        action: toggle
      style:
        top: 15%
        left: 70%
        transform: scale(2,2)
        "--paper-item-icon-color": red
        "--paper-item-icon-active-color": green
         

    # -------- Todos los enchufes ---------------

    - type: icon
      icon: mdi:power
      tap_action:
        action: call-service
        service: homeassistant.turn_off
        service_data:
          entity_id: group.regleta1                
      style:
        top: 65%
        left: 83%
        color: red
        transform: scale(2,2)
   

    - type: icon
      icon: mdi:power
      tap_action:
        action: call-service
        service: homeassistant.turn_on
        service_data:
          entity_id: group.regleta1                
      style:
        top: 65%
        left: 92%
        color: green
        transform: scale(2,2)
    

# ---------------------------------------------- REGLETA 2 ----------------------------------------------
- type: picture-elements
  image: /local/img/lovelace/regleta2v2.png
  elements:
    - type: state-icon
      icon: mdi:power
      entity: switch.enchufe_pc
      tap_action:
        action: toggle
      style:
        top: 15%
        left: 13%
        transform: scale(2,2)
        "--paper-item-icon-color": red
        "--paper-item-icon-active-color": green


    - type: state-icon
      icon: mdi:power
      entity: switch.enchufe_monitor
      tap_action:
        action: toggle
      style:
        top: 15%
        left: 32%
        transform: scale(2,2)
        "--paper-item-icon-color": red
        "--paper-item-icon-active-color": green
                    

    - type: state-icon
      icon: mdi:power
      entity: switch.enchufe_bluetooth
      tap_action:
        action: toggle
      style:
        top: 15%
        left: 51%
        transform: scale(2,2)
        "--paper-item-icon-color": red
        "--paper-item-icon-active-color": green


    - type: state-icon
      icon: mdi:power
      entity: switch.enchufe_infrarrojos
      tap_action:
        action: toggle
      style:
        top: 15%
        left: 70%
        transform: scale(2,2)
        "--paper-item-icon-color": red
        "--paper-item-icon-active-color": green
  

    # -------- Todos los enchufes ---------------

    - type: icon
      icon: mdi:power
      tap_action:
        action: call-service
        service: homeassistant.turn_off
        service_data:
          entity_id: group.regleta2                
      style:
        top: 65%
        left: 83%
        color: red
        transform: scale(2,2)
        

    - type: icon
      icon: mdi:power
      tap_action:
        action: call-service
        service: homeassistant.turn_on
        service_data:
          entity_id: group.regleta2                
      style:
        top: 65%
        left: 92%
        color: green
        transform: scale(2,2)
