
- type: state-label
  entity: sensor.carga_bateria_app
  style:
    left: 23%
    top: 3%
    transform: scale(2.5,2.5)
    title: Batería

- type: state-label
  entity: sensor.ampere_batterysoh
  style:
    left: 68%
    top: 3%
    transform: scale(1.6,1.6)

- type: state-badge
  entity: sensor.temperatura_ampere
  title: 'kk'
  style: 
    left: 14%
    top: 19%
    transform: scale(1.25,1.25)
    title: Ampere

# tuve que hacer un sensor template e igualarlo al de ampere, porque en el de ampere (modbus) no podía establecer el friendly_name

- type: state-badge
  entity: sensor.temp_inverter
  title: ''
  style:
    left: 39%
    top: 19%
    transform: scale(1.25,1.25)
    title: Inverter

- type: state-badge
  entity: sensor.temp_baterias
  title: null
  style:
    left: 65%
    top: 19%
    transform: scale(1.25,1.25)

- type: state-label
  entity: sensor.ampere_meteractivepower   #red a casa
  style:
    left: 5%
    top: 55%
    transform: scale(1.2,1.2)                  

- type: state-label
  entity: sensor.ampere_inverterpvpower  # producción total sol
  style:
    left: 78%
    top: 38%
    transform: scale(1.2,1.2)                  

- type: state-label
  entity: sensor.ampere_inverteractivepower #sol/ampere a casa
  style:
    left: 55%
    top: 55%
    transform: scale(1.2,1.2)    

# ------------------- Barra inferior ---------------------------------------

- type: state-label
  entity: sensor.ampere_alarms
  style:
    left: 15%
    top: 78%
    transform: scale(1,1)    

- type: state-label
  entity: sensor.ampere_status
  style:
    left: 15%
    top: 85%
    transform: scale(1,1)    

- type: state-label
  entity: sensor.ampere_workingmode
  style:
    left: 15%
    top: 92%
    transform: scale(1,1)    
