title: 100_start
path: start
panel: true
cards:

  - type: custom:layout-card
    layout: horizontal
    column_num: 1
    max_columns: 1
    max_width: [100%]
    cards:

      # *****************************************************************************************************************
      # **************************************************** T O P ******************************************************
      # *****************************************************************************************************************

      - type: custom:state-switch
        entity: input_boolean.topbar_config
        states:
          "off":
            !include /config/lovelace1/000_top_barv2.yaml
          "on":
            !include /config/lovelace1/000_top_barv2-2.yaml
      - type: horizontal-stack
        cards:

          - type: entities
            entities:
              - input_number.x_pos
              - input_number.y_pos
          - type: custom:gap-card
