# info y addon: https://community.home-assistant.io/t/created-new-add-on-to-backup-snapshots-to-google-drive/76737/42
- id: autobackup # Backup sábado a las 6:00
  alias: backup automático
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:00:00'
  condition:
  - condition: time
    weekday:
      - sat
  action:
  - service: script.full_backup_a_drive

# ------------------------------------------------------------------------------------------------------
# ------------------------------ PRESENCIA ENTRADA -----------------------------------------------------
# ------------------------------------------------------------------------------------------------------

- id: sonar_simbre
  alias: Sonar timbre
  trigger:
    - platform: state
      entity_id: binary_sensor.puerta_principal
      to: 'on'
#  condition:
#    - condition: state
#      entity_id: input_boolean.modo_fiesta
#      state: 'off'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        ringtone_id: '10'
        ringtone_vol: '10'

# ------------------------------------------------------------------------------------------------------      
# --------------------------------------------------- TOMAR PASTILLA ---------------------------------
# ------------------------------------------------------------------------------------------------------
#Para desactivar, decir "OK Google, activar pastilla", así se activará la booleana que lo controla 
- id: recordatorio_pastilla
  alias: Tomar pastilla
  trigger:
    platform: time_pattern
    # You can also match on interval. This will match every 5 minutes
    minutes: '/5'
  condition:
    - condition: time
      # At least one of the following is required.
      after: '22:15:00'
      before: '23:59:00'
    - condition: state
      entity_id: input_boolean.tomar_pastilla
      state: 'on'
  action:
  - service: xiaomi_aqara.play_ringtone    
    data:
      ringtone_id: '11'
      ringtone_vol: '3'
  - condition: state
    entity_id: input_boolean.avisar_pastillas_movil
    state: 'on'
  - service: telegram_bot.send_message
    data:
      message: Pastilla!!!!
      target: 440192507

      

- id: activar_recordatorio_pastilla
  alias: Activar recordatorio pastilla
  trigger:
    platform: time
    at: '21:00'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.tomar_pastilla


# ------------------------------------------------------------------------------------------------------
# ----------------------------------------- ACTIVIDAD PC -----------------------------------------------
# ------------------------------------------------------------------------------------------------------
- id: pc_pagado
  alias: PC apagado
  trigger:
    platform: state
    entity_id: binary_sensor.pc_encendido
    from: 'on'
    to: 'off'
    for: 00:02:00
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.encender_ordenador
  - condition: state
    entity_id: input_boolean.aviso_actividad_pc
    state: 'on'
  - service: telegram_bot.send_message
    data:
      message: PC apagado
      target: 440192507
      
      
- id: PC_encendido
  alias: PC encendido
  trigger:
    platform: state
    entity_id: binary_sensor.pc_encendido
    from: 'off'
    to: 'on'
    for: 00:02:00
  action:
  - condition: state
    entity_id: input_boolean.aviso_actividad_pc
    state: 'on'
  - service: telegram_bot.send_message
    data:
      message: PC encendido
      target: 440192507

# ------------------------------------------------------------------------------------------------------
# ---------------------------------- ENCENDER ORDENADOR --------------------------------------------
# ------------------------------------------------------------------------------------------------------

- id: encender_ordenador
  alias: Encender ordenador
  trigger:
  - entity_id: input_boolean.encender_ordenador
    platform: state
    to: 'on'    
  condition:
    - condition: state
      entity_id: binary_sensor.pc_encendido
      state: 'off'
      
  action:
  - service: switch.turn_off
    entity_id: switch.enchufe_pc
  - delay: 00:00:05
  - service: switch.turn_on
    entity_id: switch.enchufe_monitor
  - service: switch.turn_on
    entity_id: switch.enchufe_pc
  - delay: 00:00:05
  - service: switch.turn_on
    entity_id: switch.wake_on_lan
  - service: input_boolean.turn_off
    entity_id: input_boolean.encender_ordenador



# ------------------------------------------------------------------------------------------------------
# ---------------------------------- NUEVAS ACTUALIZACIONES --------------------------------------------
# ------------------------------------------------------------------------------------------------------
# https://community.home-assistant.io/t/updater-card-to-show-new-version/100923/3
- id: nuevas_actualizaciones
  alias: Actualización Disponible
  trigger:
    platform: state
    entity_id: sensor.version_available
  condition:
    - condition: template
      value_template: >-
        {{
          states('sensor.version_available')
          !=
          states('sensor.version_current')
        }}
  action:
    - service: persistent_notification.create
      data_template:
        title: Upgrade time!
        message: >-
          There is a Home Assistant upgrade for Hass.io pending!
          Version {{ states('sensor.version_available') }} just got released!
        notification_id: hassio_upgrade

    - service: telegram_bot.send_message
      data:
        message: Ha salido una nueva actualización de Home Assistant
        target: 440192507

    - service: notify.correo_jam
      data_template:
        title: 'HA: IMPORTANTE'
        target:
          - jordiaguileram@gmail.com
        message: >-
          There is a Home Assistant upgrade for Hass.io pending!
          Version {{ states('sensor.version_available') }} just got released!


# ------------------------------------------------------------------------------------------------------
# -------------------------------------------- A DORMIR  -----------------------------------------------
# ------------------------------------------------------------------------------------------------------

- id: preaviso_dormir  # De domingo a viernes, los días de cole
  alias: Preaviso dormir
  trigger:
  - platform: time
    at: '21:40'
  condition:
    - condition: template  # 0: lunes
      value_template: "{{ now().weekday() in (6,0,1,2,3) }}"
    - condition: state
      entity_id: 'input_select.hay_cole' 
      state: Si
  action:
  - service: script.notificacion_google
    data:  
      mensaje: Son las 10 menos 20. Preparándose para ir a dormir
      volumen: 0.6

- id: avisodormir
  alias: Aviso dormir
  trigger:
  - platform: time
    at: '21:50'
  condition:
    - condition: template  # 0: lunes
      value_template: "{{ now().weekday() in (6,0,1,2,3) }}"
    - condition: state
      entity_id: 'input_select.hay_cole' 
      state: Si
  action:
  - service: script.notificacion_google
    data:
      mensaje: Pijama, dientes y a dormir
      volumen: 0.6

- alias: Alerta metereológica
  trigger:
    platform: state
    entity_id: binary_sensor.meteoalarm
    from: ‘off’
  action:

    - service: telegram_bot.send_message
      data_template:
        message: >-
            "{{state_attr('binary_sensor.meteoalarm', 'headline')}}"
            "{{state_attr('binary_sensor.meteoalarm', 'description')}} is effective on {{state_attr('binary_sensor.meteoalarm', 'effective')}}"
        target: 440192507
    
    - service: persistent_notification.create
      data_template:
        title: "{{state_attr('binary_sensor.meteoalarm', 'headline')}}"
        message: >-
          "{{state_attr('binary_sensor.meteoalarm', 'description')}} is effective on {{state_attr('binary_sensor.meteoalarm', 'effective')}}"
        notification_id: alerte_metereologica


# ------------------------------------------------------------------------------------------------------      
# ----------------------------------------------- AL COLE ----------------------------------------------   
# ------------------------------------------------------------------------------------------------------
- id: preaviso_cole
  alias: Pre aviso cole
  trigger:
  - at: 08:30
    platform: time
  condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor' 
      state: 'on'
    - condition: state
      entity_id: 'input_select.hay_cole' 
      state: Si
  action:
    - service: script.notificacion_google
      data:  
        mensaje: "Son las 8:30. A lavarse los dientes y preparar la mochila" 
        volumen: 0.7
    - delay: '00:01:00'
    - condition: state
      entity_id: 'input_select.hay_cole' 
      state: Si
    - service: script.notificacion_google
      data:  
        mensaje: "Son las 8:40. Faltan 5 minutos para ir al cole" 
        volumen: 0.7
    - delay: '00:01:00'
    - condition: state
      entity_id: 'input_select.hay_cole' 
      state: Si
    - service: script.notificacion_google
      data:  
        mensaje: "Son las 8:45. Hora de ir al cole. Apagando la tele en 15 segundos" 
        volumen: 0.7
    - delay: 00:00:15
    - service: media_player.turn_off
      entity_id: media_player.lg
    - delay: 00:00:05
    - service: script.notificacion_google
      data:  
        mensaje: "Que tengáis todos un buen día"       
        volumen: 0.7

# --------------------------------------------------------------------------------------------------------------------------------
# ----- Si se va el suministro eléctrico, cuando vuelve apaga las luces, que por defecto se encienden todas ----------------------
# --------------------------------------------------------------------------------------------------------------------------------

- id: redelectrica_apagada
  alias: Red eléctrica apagada
  trigger:
    - platform: state
      entity_id: binary_sensor.philips_bridge
      from: 'on'
      to: 'off'
      for: 00:01:00 # si no ponemos tiempo, aun encontrarà online_internet a on
    - platform: state
      entity_id: binary_sensor.nevera
      from: 'on'
      to: 'off'
      for: 00:01:00
  condition: 
    - condition: state
      entity_id: binary_sensor.online_internet
      state: 'on'
  action:
  - service: input_boolean.turn_on # para distinguir de cuando cae internet
    entity_id: input_boolean.red_electrica_caida
  - service: telegram_bot.send_message
    data:
      message: Ha caído red eléctrica
      target: 440192507
     
- id: redelectrica_encendida
  alias: Red eléctrica encendida
  trigger:
    - platform: state
      entity_id: binary_sensor.philips_bridge
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.nevera
      from: 'of'
      to: 'on'
  condition: 
    - condition: state
      entity_id: input_boolean.red_electrica_caida
      state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.red_electrica_caida  
  - service: telegram_bot.send_message
    data:
      message: Red eléctrica recuperada
      target: 440192507
    # encendemos enchufe wemo del aire acondicionado
  - service: switch.turn_on
    entity_id: switch.enchufe_aire
    # y apagamos luces, ya que se encienden solas al volver la luz
  - delay: 00:00:30
  - service: light.turn_off
    entity_id: light.luces_piso

# ------------------------------------------------------------------------------------------------------      
# ----------------------------------------------- VARIOS ----------------------------------------------   
# ------------------------------------------------------------------------------------------------------

- id: internet_online
  alias: Internet Online
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.online_internet
    from: 'off'
    to: 'on'
    for: 00:00:10
  action:
  - service: telegram_bot.send_message
    data_template:
      message: >-
        Reestablecida conexión Internet. Hora de caída: {{ states ('input_text.hora_caida_internet')}}. Hora de recuperación: {{ states('sensor.date_time') }}
      target: 440192507


  # Guarda hora caída internet, para avisar al restablecer
- alias: guarda hora
  trigger:
    platform: state
    entity_id:  binary_sensor.online_internet
    from: 'on'
    to: 'off'
    for: 00:00:10
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.hora_caida_internet
        value: "{{ states('sensor.date_time') }}"

################################################ VOLUMEN SUPERYO ######################################################
- id: volumen_bajo
  alias: Volumen google home bajo
  trigger:
  - at: '22:10'
    platform: time
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.superyo
      volume_level: 0.5

- id: volumen_alto
  alias: Volumen google home alto
  trigger:
  - at: '07:45'
    platform: time
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.superyo
      volume_level: 0.7