homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

default_config:

http:
  base_url: !secret duckdns
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem




# --------------------------------------------------------------------------------------
# ------------------------------ Google Home -------------------------------------------
# --------------------------------------------------------------------------------------

# https://domology.es/integracion-de-google-home-en-home-assistant/
google_assistant:
  project_id: !secret google_home 
  exposed_domains:
    - switch
    - light
    - input_boolean
    - media_player
    - automation  
    - scene
    - script      
    - vacuum
  entity_config: !include dispositivosGH.yaml


#https://www.home-assistant.io/integrations/calendar.google
google:
  client_id: !secret calendar_id 
  client_secret: !secret calendar_secret 

tts:
  - platform: google_translate
    cache: false
    #cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://192.168.1.100:8123
    service_name: google_say
    language: es

rest_command:
  google_backup:
    url: 'http://localhost:8055/gbdoBackup'
    timeout: '300'   

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 440192507

# https://darksky.net/dev/docs
# si en PLANTILLAS escribo {{ states.weather.dark_sky }}, veré todo lo que ofrece. En la carpeta APUNTS hay
# un ejemplo de cómo acceder a todos los campos
weather:
  - platform: darksky
    api_key: !secret api_darksy
    mode: daily   # sino el tiempo de lovelace lo muestra por horas


xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_key
      mac: !secret xiaomi_mac
      host: 192.168.1.11      

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.101
    token: !secret vacuum_token
    name: Aspirino


wake_on_lan:



# https://www.home-assistant.io/integrations/webostv/
webostv:
  - host: 192.168.1.203
    name: LG
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        # mac: "2c:2b:f9:70:3b:64"   wifi
        "mac": "A8:23:FE:C1:6A:CE"  # cable
    customize:
      sources:
        - livetv
        - youtube
        - netflix

notify:
  - name: correo_jam
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret user_gmail
    encryption: starttls
    username: !secret user_gmail
    password: !secret pwd_gmail
    recipient: !include direcciones.yaml
    sender_name: Notificación Home Assistant
    #debug: True


#  - name: Pocophone     # lannouncer: instalando app, recibe mensajes de voz
#    platform: lannouncer
#    host: 192.168.1.55
# Con la tablet de martí, a la mínima deja de funcionar. Tampoco auto start up


# ----------------------- Establece qué grabamos y qué no --------------------
# https://www.home-assistant.io/components/recorder/
# https://community.home-assistant.io/t/rpi-hassio-synology-nas-maria-db-for-logging/64012

recorder:
  db_url: mysql://jordiam:5SCwf9kTyezdGqp@192.168.1.9:3307/ha_2020?charset=utf8
  purge_keep_days: 21   # días a mantener después del purge
  purge_interval: 1
  exclude:
    event_types:
      - call_service
      - hacs/repository
  include:
    domains:
      - sensor

# https://www.home-assistant.io/integrations/history/
# history: en principio no ponemos nada, entonces lo hará de los mismo elementos del recorder


device_tracker:
    # 51: S6 jordi, 52 Xiaomi Ana  54: Madre Ana  55: pocophone F1
  - platform: nmap_tracker
    hosts: 
      - 192.168.1.52-55
      - 192.168.1.201  #Tablet Martí
    interval_seconds: 60
    consider_home: 180

# Enables map tracking of devices
map:


browser_mod:
  devices:
    03a926fb-96f2f8b6:
      name: pccasa
    d60ff5dc-07b2a0df:
      name: dashboard

#********************************************************************************************************************
#
#                                              M E D I A   P L A Y E R S 
#
#********************************************************************************************************************

media_player: # -----------------------------------------------------------------------------------------------------------------
  - platform: yamaha_musiccast
    host: 192.168.1.31
    port: 5005
    
  - platform: yamaha_musiccast
    host: 192.168.1.32
    port: 5006
    
  - platform: yamaha_musiccast
    host: 192.168.1.30
    port: 5007

#https://developer.spotify.com/dashboard/login -> Spotify2020
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

#********************************************************************************************************************
#
#                                                  L U C E S 
#
#********************************************************************************************************************

hue:
  bridges:
    - host: 192.168.1.23
      allow_unreachable: true
      allow_hue_groups: true


light:

# Xiaomi Philips light
# de momento la desactivo, porque siempre está apagada, y entonces da errores constantes

#  - platform: xiaomi_miio
#    name: Luz Nil
#    host: 192.168.1.13
#    token: !secret light_token  
    
  - platform: limitlessled  # Leds
    bridges:
      - host: 192.168.1.210
#        version: 6
#        version: 4 5 6 SI
#        port: 8899
        groups:
        - number: 1
          name: Mueble
          type: rgbww
        - number: 2
          name: Cortina
          type: rgbww
        - number: 3
          name: Ventana
          type: rgbww



# Enables the frontend themes
frontend:
  themes: !include_dir_merge_named themes

sun:

# https://www.home-assistant.io/lovelace/dashboards-and-views/
# Para gestionar varios paneles



lovelace:
  resources: !include resources.yaml
  mode: yaml
  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: ui-dash2.yaml
      title: Pruebas
      icon: mdi:tools
      show_in_sidebar: true




group: !include groups.yaml
#automation: !include automations.yaml
automation: !include_dir_merge_list automation/   # <-- esto lee todos los ficheros de esta carpeta
script: !include scripts.yaml
scene: !include scenes.yaml
