#https://www.home-assistant.io/docs/configuration/customizing-devices/
switch.xiaomi: #Para no apagar involuntariamente
  hidden: true

sensor.playlist:
  hidden: true
sensor.playlist2:
  hidden: true
sensor.playlist3:
  hidden: true
sensor.playlist4:
  hidden: true
sensor.playlist5:
  hidden: true


sensor.temperatura_ampere:
  friendly_name: ' ' # para que no aparezca en el picture-element

device_tracker.bici:
  entity_picture: /local/img/lovelace/orbea.png      

sensor.spain_coronavirus_deaths:
  unit_of_measurement: 'Fallecidos'

sensor.spain_coronavirus_confirmed:
  unit_of_measurement: 'Contagio'