escenas:
  name: Escenas
  entities:
    - input_boolean.luces_principales
    - input_boolean.luces_traseras
    - input_boolean.luces_cruz
    # - input_boolean.luces_led
    - input_boolean.luces_todas
    - input_boolean.luces_cenando
    - input_boolean.luces_relax
    - input_boolean.luces_cine

#botones_tiempo:
#  name: botones mapa tiempo
#  entities:
#    - input_boolean.boton1
#    - input_boolean.boton2
#    - input_boolean.boton3
#    - input_boolean.boton4


regleta1:
  name: Regleta 1
  entities:
    - switch.enchufe_canal_plus
    - switch.enchufe_libre
    - switch.enchufe_nvidia
    - switch.enchufe_pioneer

regleta2:
  name: Regleta 2
  entities:
    - switch.enchufe_pc
    - switch.enchufe_monitor
    - switch.enchufe_bluetooth
    - switch.enchufe_infrarrojos