  ################################################ H A C S ####################################################################
  #                                                                                                                           #

- url: /hacsfiles/spotify-playlist-card/spotify-playlist-card.js
  type: js      

  # Para modo kiosko
  # https://192.168.1.40:8123/lovelace/0?disable_ch      para mostrarlo desactivado
- url: /hacsfiles/custom-header/custom-header.js
  type: module

  # Agrupa entidades de diferentes maneras
- url: /hacsfiles/lovelace-auto-entities/auto-entities.js
  type: module

- url: /hacsfiles/atomic_calendar/atomic_calendar.js
  type: module

- url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
  type: module

  # Xiaomi vacuum  https://github.com/benct/lovelace-xiaomi-vacuum-card
- url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
  type: module

  # https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
- url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
  type: module

  #https://github.com/thomasloven/lovelace-layout-card - Get more control over the placement of lovelace cards
- url: /hacsfiles/lovelace-layout-card/layout-card.js
  type: module

  # This is not a new card. Instead it changes the way pretty much any other card works.
- url: /hacsfiles/lovelace-card-mod/card-mod.js
  type: module

  # Para los botones de los mapas del tiempo
- url: /hacsfiles/button-card/button-card.js
  type: module

- url: /hacsfiles/lovelace-gap-card/gap-card.js
  type: module

- url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  type: module


 #- url: /hacsfiles/power-wheel-card/power-wheel-card.js
 #  type: module

- url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  type: module

- url: /hacsfiles/light-entity-card/light-entity-card.js
  type: js

# Al final lo hago "a mano"
#- url: /local/community/battery-state-card/battery-state-card.js
#  type: module

- url: /hacsfiles/bar-card/bar-card.js
  type: module
  
  # problemas de compatibilidad. Substituido el js por el encontrado en https://github.com/Lau-ie/flex-horseshoe-card/tree/0.106.x-compatibility
  # foro problemas y explica como instalar el nuevo: https://community.home-assistant.io/t/lovelace-flexible-horseshoe-card-donut-graph-flexible-layout-multiple-entities-actions-animations-including-next-gen-experimental-examples/137850/103

- url: /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js
  type: module
  
- url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  type: js  

- url: /hacsfiles/plan-coordinates/plan-coordinates.js
  type: module

- url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
  type: module


  # https://github.com/thomasloven/lovelace-state-switch: muestra una tarjeta u otra según condición. Usada para HorseShoe cuando no iba en PC
- url: /hacsfiles/lovelace-state-switch/state-switch.js
  type: module

  #                                                                                                                           #
  #############################################################################################################################

# https://github.com/robmarkoski/ha-clockwork-card
- url: /local/plugins/clockwork-card.js?v=0.1.2
  type: js

# También se podría tener en local
- url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
  type: module

  # podemos verlas en https://fonts.google.com/
- url: 'https://fonts.googleapis.com/css?family=Quicksand:300,400'
  type: css
- url: https://fonts.googleapis.com/css2?family=Audiowide
  type: css