# info y addon: https://community.home-assistant.io/t/created-new-add-on-to-backup-snapshots-to-google-drive/76737/42
full_backup_a_drive:  
  alias: Crea backup completo y sube a drive
  sequence:
    - service: hassio.snapshot_full
      data_template:
        name: Backup automático {{ now().strftime('%Y-%m-%d') }}
    - service: telegram_bot.send_message
      data_template:
        message: Creating backup named Backup automático {{ now().strftime('%Y-%m-%d') }}
        target: 440192507
    - delay: "00:30:00"
    - service: rest_command.google_backup
    - service: telegram_bot.send_message
      data:
        message: Backup finalizado
        target: 440192507
#--------------------------------------------------------------------------------------------------------------------

test_telegram:  
  alias: Testea funcionamiento telegram
  sequence:
    - service: telegram_bot.send_message
      data:
        message: Testeando telegram
        target: 440192507
#--------------------------------------------------------------------------------------------------------------------

test_google_tts:      # Hecho
  alias: Testea funcionamiento google
  sequence:
    - service: script.notificacion_google
      data:
        mensaje: "15 minutos para apagar la tablet"
        volumen: 0.5

#------------------------------------------------- NOTIFICACIONES GOOGLE TTS -----------------------------------------
notificacion_google:      # Hecho
  alias: Notificación google
  description: 'Lee mensaje en superyo a volumen especificado (0.5 si no se especifica)'
  fields:
    mensaje:
      description: 'Texto a leer'
      example: 'Hola mundo!'
    volumen:
      description: 'Volumen altavoz (opcional)'
      example: '0.7'
  sequence:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.backup_volumen
      value: >
        {% if (state_attr('media_player.superyo','volume_level')==None) %} 
        0.5
        {% else %}
        {{ state_attr('media_player.superyo','volume_level') }}
        {% endif %}
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.superyo
      volume_level: >
        {% if volumen is defined %}
          {{ volumen }}
        {% else %}
           {% if now().hour < 7 %}
              0.4
           {% elif now().hour < 22 %}
              0.6
           {% else %}
              0.4
           {% endif %} 
        {% endif %}
  - service: tts.google_say
    entity_id: media_player.superyo
    data_template:
      message: >
          {{ mensaje }}
  - delay: '00:00:20'
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.superyo
      volume_level: >
        {{ states('input_number.backup_volumen') }}

# Enciende la luz del HUB Xiaomi segun color en formato hexadecimal
alerta_luz_hub:
  sequence:
    - service: light.turn_on
      entity_id: light.xiaomi
      data_template:
        rgb_color:
          - '{{ what_color[0:2]|int(0,16) }}'
          - '{{ what_color[2:4]|int(0,16) }}'
          - '{{ what_color[4:6]|int(0,16) }}'

