# info y addon: https://community.home-assistant.io/t/created-new-add-on-to-backup-snapshots-to-google-drive/76737/42
full_backup_a_drive:  
  alias: Crea backup completo y sube a drive
  sequence:
    - service: hassio.snapshot_full
      data_template:
        name: Backup automático {{ now().strftime('%Y-%m-%d') }}
    - service: telegram_bot.send_message
      data_template:
        message: Creating backup named Backup automático {{ now().strftime('%Y-%m-%d') }}
        target: 440192507
    - delay: "00:30:00"
    - service: rest_command.google_backup
    - service: telegram_bot.send_message
      data:
        message: Backup finalizado
        target: 440192507
#--------------------------------------------------------------------------------------------------------------------

test_telegram:  
  alias: Testea funcionamiento telegram
  sequence:
    - service: telegram_bot.send_message
      data:
        message: Testeando telegram
        target: 440192507
#--------------------------------------------------------------------------------------------------------------------

test_google_tts:      # Hecho
  alias: Testea funcionamiento google
  sequence:
  - service: tts.google_say
    entity_id: media_player.superyo
    data:
      message: Son las {{(as_timestamp (now()) + (states("input_number.sleep_timer_duration") | int) *60) | timestamp_custom ("%H:%M:%S", true)}}

notificacion_google:      # Hecho
  alias: Notificación google
  sequence:
  - service: tts.google_say
    entity_id: media_player.superyo
    data_template:
      message: >
          {{ mensaje }}

# Enciende la luz del HUB Xiaomi segun color en formato hexadecimal
alerta_luz_hub:
  sequence:
    - service: light.turn_on
      entity_id: light.xiaomi
      data_template:
        rgb_color:
          - '{{ what_color[0:2]|int(0,16) }}'
          - '{{ what_color[2:4]|int(0,16) }}'
          - '{{ what_color[4:6]|int(0,16) }}'



test_popup:      
  sequence:
  - service: persistent_notification.create
    data:
      message: Popup


# Si el switch está activado, también avisa de recordatorio pastilla al móvil
telegram_pastilla:
  alias: telegram recordatorio pastilla
  sequence:
    - condition: state
      entity_id: input_boolean.avisar_pastillas_movil
      state: 'on'
    - service: telegram_bot.send_message
      data:
        message: Pastilla!!!!
        target: 440192507
