title: Mi casa


# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/local/background-low.jpg") fixed
background: center / cover no-repeat url("/local/img/background_19.png") fixed


custom_header:
  kiosk_mode: '{{ states.input_boolean.modo_kiosko.state  == "on" }}'
  background: 'rgba(150, 150, 150, 0.2)'
  menu_hide: false
  options_hide: false
  voice_hide: false
  clock_format: '24'
  clock_date: true
  date_locale: es-ES
  header_text: '{{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true


# https://www.home-assistant.io/lovelace/views/
views:
  

  - !include /config/lovelace1/100_start.yaml    
#  - !include /config/lovelace/200_lights.yaml
#  - !include /config/lovelace/300_eltiempo.yaml
#  - !include /config/lovelace/400_ampere.yaml
#  - !include /config/lovelace/450_xiaomi.yaml
#  - !include /config/lovelace/500_musica.yaml    
#  - !include /config/lovelace/520_spotify.yaml
#  - !include /config/dash2/30_media_pruebas.yaml
#  - !include /config/lovelace/550_tv.yaml  
#  - !include /config/lovelace/575_tp.yaml    
#  - !include /config/lovelace/600_bici.yaml      
#  - !include /config/lovelace/700_pi.yaml
#  - !include /config/lovelace/800_ayuda.yaml
#  - !include /config/lovelace/900_config.yaml
#  - !include /config/lovelace/250_lights2d.yaml 
#  - !include /config/lovelace/050_index.yaml
#  - !include /config/lovelace/510_musica.yaml  


    